version: '3.8'

services:
  rest-api:
    build: ./rest_api
    container_name: chat_rest_api
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: always

  websocket:
    build: ./websocket_gateway
    container_name: chat_websocket_gateway
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
    restart: always

  db:
    image: postgres:15
    container_name: chat_postgres
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: chat_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata: 